const dataTable = [
    {
        id: "1",
        status: "Disponível",
        name: "",
        capacity: 0,
        screens: 0,
        keyboard: false,
        mouse: false,
        webcam: false,
        headset: false,
        description: "teste 4",
        isBlocked: false,
        local: "3º andar - Estação 1",
    },
    {
        id: "2",
        status: "Ocupado",
        name: "",
        capacity: 0,
        screens: 0,
        keyboard: false,
        mouse: false,
        webcam: false,
        headset: false,
        description: "teste 2",
        isBlocked: false,
        local: "2º andar - Estação 4",
    },
    {
        id: "3",
        status: "Disponível",
        name: "",
        capacity: 0,
        screens: 0,
        keyboard: false,
        mouse: false,
        webcam: false,
        headset: false,
        description: "teste 1",
        isBlocked: false,
        local: "1º andar - Estação 3",
    },
    {
        id: "4",
        status: "Bloqueado",
        name: "",
        capacity: 0,
        screens: 0,
        keyboard: false,
        mouse: false,
        webcam: false,
        headset: false,
        description: "teste 6",
        isBlocked: false,
        local: "2º andar - Estação 2",
    },
];

module.exports = {
    dataTable
}